### ISSUE TITLE
ActionController::HandleUnpermittedParameters doesn't seem to handle Attachinary

### ISSUE THREAD

**Issue by schwagogo** [IndieGoGo/params_patrol#2]
This is the controller action we're working on:

```
  def update_cloudinary_image
    @logo = Logo.find(params[:logo_id])
    @logo.update_attributes!(cloudinary_image: image_params)
    render text: 'ok'
  end

  def image_params
    params.require(:image_params).permit(:public_id, :version, :resource_type)
  end
```

This is the test we wrote to test that params_patrol would log unrecognized params instead of exploding:

```
    it 'should catch unpermitted params without erroring out' do
      expect(ParamsPatrol).to receive(:handle)
      VCR.use_cassette('cloudinary/confirm_params') {
        post :update_cloudinary_image, logo_id: logo1.id, image_params: {
                                       public_id: 'newpublicid',
                                       version: '1424471696',
                                       resource_type: 'image',
                                       unrecognized: 'param'
                                     }
      }
      expect(response).to be_success
    end
```

Without `ActionController::HandleUnpermittedParameters` in the controller, the test fails with 

```
ActionController::UnpermittedParameters: found unpermitted parameters: unrecognized
./app/controllers/admin/logos_controller.rb:60:in `image_params'
```

which is what we expect.

With the module included, we get

```
ActiveRecord::AssociationTypeMismatch: ::Attachinary::File(#70250706916660) expected, got ActionController::DecoratesParameters(#70250706502980)
./app/controllers/admin/logos_controller.rb:38:in `update_cloudinary_image'
```

`.permit` no longer explodes, which is great, but Attachinary seems to not like `DecoratesParameters`.

**Comment by schwagogo** [comment]
@GoGoAmanda is equally culpable for this issue report.

**Comment by schwagogo** [comment]
/)*(\
